proxy_cache_path /var/cache/nginx/proxy keys_zone=static_assets:10m inactive=365d;

server {
    listen 3000;

    location ~* \.(css|js)$ {
        proxy_pass http://backend:3001;
        proxy_cache static_assets;
        proxy_cache_valid 200 7d;
        proxy_ignore_headers Vary;
    }

    location / {
        proxy_pass http://backend:3001;
    }
}
